name: Release
on:
  pull_request:
    types: [ labeled ]
    branches:
      - '**/release/v[0-9]+.[0-9]+.[0-9]+'
jobs:
  pipeline:
    name: sekhmetApi Release push
    runs-on: ubuntu-latest
    if: "github.event.label.name == 'release_push' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 14.18.1
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install node.js packages
        run: npm install

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers: |
            [
              {
                "id": "sekhmet-api-snapshots",
                "username": "${{ secrets.ARTIFACTORY_USERNAME_REF }}",
                "password": "${{ secrets.ARTIFACTORY_PASSWORD_REF }}"
              }
            ]
      - name: Configure Git user
        run: |
          git config user.email "dev.sekhmet@gmail.com"
          git config user.name "Dev Sekhmet"

      - name: Push Release
        run: |
          chmod +x mvnw
          npm run java:jar:push:release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CI_TOKEN }}

      - name: Jar file
        uses: actions/upload-artifact@v2
        with:
          name: JarFile
          path: target/sekhmet*.jar
          retention-days: 30
